@Storage_WebApi_HostAddress = http://localhost:5246

POST {{Storage_WebApi_HostAddress}}/api/invoice
Content-Type: application/json

{
    "TotalAmount": 99.99,
    "Base64Content": "VGhpcyBpcyBhIHNhbXBsZSBpbnZvaWNlIGJpbmFyeSBjb250ZW50Lg=="
}

###

GET {{Storage_WebApi_HostAddress}}/api/invoice?invoiceId=3f4020af-13dc-4364-adec-009b33b49b4b
